// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace ContosoUniversity.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240408014510_AdditionalFieldsForRefreshToken")]
    partial class AdditionalFieldsForRefreshToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CourseId");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ba22eae4-8282-483d-8d43-e3b47bd105d4"),
                            Credits = 3,
                            DepartmentId = new Guid("ce1815fb-6730-4b7a-9e3c-322db0c98414"),
                            Title = "Chemistry"
                        },
                        new
                        {
                            Id = new Guid("854f1892-e043-49e0-9573-5544e833a8d3"),
                            Credits = 3,
                            DepartmentId = new Guid("00c4512a-6c05-482b-9026-3f413f477132"),
                            Title = "Microeconomics"
                        },
                        new
                        {
                            Id = new Guid("ad18dff5-58ee-4e02-ba83-ffd1c8a1f56e"),
                            Credits = 3,
                            DepartmentId = new Guid("00c4512a-6c05-482b-9026-3f413f477132"),
                            Title = "Macroeconomics"
                        },
                        new
                        {
                            Id = new Guid("db564e68-2fe5-42e5-ba48-b2b49034d3d2"),
                            Credits = 4,
                            DepartmentId = new Guid("c8eee19f-7040-492f-81c8-62cbe50d8467"),
                            Title = "Calculus"
                        },
                        new
                        {
                            Id = new Guid("83af998c-0bfd-4855-8c5a-4e1920b9d025"),
                            Credits = 4,
                            DepartmentId = new Guid("c8eee19f-7040-492f-81c8-62cbe50d8467"),
                            Title = "Trigonometry"
                        },
                        new
                        {
                            Id = new Guid("597800e1-0267-4ba0-81dd-a0f07aa98b20"),
                            Credits = 3,
                            DepartmentId = new Guid("c19f20e6-e77d-492d-bbc2-dce3c7603448"),
                            Title = "Composition"
                        },
                        new
                        {
                            Id = new Guid("b178e749-1f02-4461-8e5d-bb97c49eb375"),
                            Credits = 4,
                            DepartmentId = new Guid("c19f20e6-e77d-492d-bbc2-dce3c7603448"),
                            Title = "Literature"
                        });
                });

            modelBuilder.Entity("Entities.Models.CourseAssignment", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CourseId", "InstructorId");

                    b.HasIndex("InstructorId");

                    b.ToTable("CourseAssignments");

                    b.HasData(
                        new
                        {
                            CourseId = new Guid("ba22eae4-8282-483d-8d43-e3b47bd105d4"),
                            InstructorId = new Guid("e24a644d-9a45-4f66-966c-580fd191573a")
                        },
                        new
                        {
                            CourseId = new Guid("ba22eae4-8282-483d-8d43-e3b47bd105d4"),
                            InstructorId = new Guid("63b92923-68a5-4053-9bf7-5e41c4fe1d91")
                        },
                        new
                        {
                            CourseId = new Guid("854f1892-e043-49e0-9573-5544e833a8d3"),
                            InstructorId = new Guid("455dfcc1-552a-45fa-b94e-d973906490cc")
                        },
                        new
                        {
                            CourseId = new Guid("ad18dff5-58ee-4e02-ba83-ffd1c8a1f56e"),
                            InstructorId = new Guid("455dfcc1-552a-45fa-b94e-d973906490cc")
                        },
                        new
                        {
                            CourseId = new Guid("db564e68-2fe5-42e5-ba48-b2b49034d3d2"),
                            InstructorId = new Guid("2a12c3f2-fc7a-4bd2-9f66-21a9c79d1893")
                        },
                        new
                        {
                            CourseId = new Guid("83af998c-0bfd-4855-8c5a-4e1920b9d025"),
                            InstructorId = new Guid("63b92923-68a5-4053-9bf7-5e41c4fe1d91")
                        },
                        new
                        {
                            CourseId = new Guid("597800e1-0267-4ba0-81dd-a0f07aa98b20"),
                            InstructorId = new Guid("5b225eaa-ca3e-461d-85be-fb4608f87148")
                        },
                        new
                        {
                            CourseId = new Guid("b178e749-1f02-4461-8e5d-bb97c49eb375"),
                            InstructorId = new Guid("5b225eaa-ca3e-461d-85be-fb4608f87148")
                        });
                });

            modelBuilder.Entity("Entities.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DepartmentId");

                    b.Property<decimal>("Budget")
                        .HasColumnType("money");

                    b.Property<Guid?>("InstructorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c19f20e6-e77d-492d-bbc2-dce3c7603448"),
                            Budget = 350000m,
                            InstructorId = new Guid("5b225eaa-ca3e-461d-85be-fb4608f87148"),
                            Name = "English",
                            StartDate = new DateTime(2007, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c8eee19f-7040-492f-81c8-62cbe50d8467"),
                            Budget = 100000m,
                            InstructorId = new Guid("2a12c3f2-fc7a-4bd2-9f66-21a9c79d1893"),
                            Name = "Mathematics",
                            StartDate = new DateTime(2007, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ce1815fb-6730-4b7a-9e3c-322db0c98414"),
                            Budget = 350000m,
                            InstructorId = new Guid("63b92923-68a5-4053-9bf7-5e41c4fe1d91"),
                            Name = "Engineering",
                            StartDate = new DateTime(2007, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00c4512a-6c05-482b-9026-3f413f477132"),
                            Budget = 100000m,
                            InstructorId = new Guid("e24a644d-9a45-4f66-966c-580fd191573a"),
                            Name = "Economics",
                            StartDate = new DateTime(2007, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EnrollmentId");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00b87678-f3cc-4c56-93d9-47e44bcb7be3"),
                            CourseId = new Guid("ba22eae4-8282-483d-8d43-e3b47bd105d4"),
                            Grade = 0,
                            StudentId = new Guid("06917677-cdd6-4523-91b8-88d6d0a912d2")
                        },
                        new
                        {
                            Id = new Guid("624ad1c2-ae05-423a-911c-f229cd6286e4"),
                            CourseId = new Guid("854f1892-e043-49e0-9573-5544e833a8d3"),
                            Grade = 2,
                            StudentId = new Guid("06917677-cdd6-4523-91b8-88d6d0a912d2")
                        },
                        new
                        {
                            Id = new Guid("175725e5-362b-427e-91a2-69014f4e1a73"),
                            CourseId = new Guid("ad18dff5-58ee-4e02-ba83-ffd1c8a1f56e"),
                            Grade = 1,
                            StudentId = new Guid("06917677-cdd6-4523-91b8-88d6d0a912d2")
                        },
                        new
                        {
                            Id = new Guid("d308dc85-57ee-4c3a-8b90-d0a979c2299c"),
                            CourseId = new Guid("db564e68-2fe5-42e5-ba48-b2b49034d3d2"),
                            Grade = 1,
                            StudentId = new Guid("798acf1b-7339-44bd-8367-7132a978d7b1")
                        },
                        new
                        {
                            Id = new Guid("17ebb2e3-f554-4bb5-a6a1-ed92d15e6722"),
                            CourseId = new Guid("83af998c-0bfd-4855-8c5a-4e1920b9d025"),
                            Grade = 1,
                            StudentId = new Guid("798acf1b-7339-44bd-8367-7132a978d7b1")
                        },
                        new
                        {
                            Id = new Guid("c2c3f453-3b98-4c4a-91d5-c52cbfe8166b"),
                            CourseId = new Guid("597800e1-0267-4ba0-81dd-a0f07aa98b20"),
                            Grade = 1,
                            StudentId = new Guid("798acf1b-7339-44bd-8367-7132a978d7b1")
                        },
                        new
                        {
                            Id = new Guid("3c0f3598-f8fd-4929-bd40-c18733e01fca"),
                            CourseId = new Guid("ba22eae4-8282-483d-8d43-e3b47bd105d4"),
                            StudentId = new Guid("2a36409f-6732-459b-b7d1-a561c521a3cb")
                        },
                        new
                        {
                            Id = new Guid("a5dd133d-fc93-42a2-926f-9f4f33ee51e1"),
                            CourseId = new Guid("854f1892-e043-49e0-9573-5544e833a8d3"),
                            Grade = 1,
                            StudentId = new Guid("2a36409f-6732-459b-b7d1-a561c521a3cb")
                        },
                        new
                        {
                            Id = new Guid("f4ae022d-f952-4ee8-9b76-7eb82c6d6d26"),
                            CourseId = new Guid("ba22eae4-8282-483d-8d43-e3b47bd105d4"),
                            Grade = 1,
                            StudentId = new Guid("7d84360e-4967-4c7b-8e4c-0f085de7ca4d")
                        },
                        new
                        {
                            Id = new Guid("b0c84772-59be-4c9d-a8a2-a0eacb2ab607"),
                            CourseId = new Guid("597800e1-0267-4ba0-81dd-a0f07aa98b20"),
                            Grade = 1,
                            StudentId = new Guid("7a1be69a-38ac-4cde-a105-615de38c2d12")
                        },
                        new
                        {
                            Id = new Guid("1fa1bbf9-0be1-4908-b850-19b5d246ecb9"),
                            CourseId = new Guid("b178e749-1f02-4461-8e5d-bb97c49eb375"),
                            Grade = 1,
                            StudentId = new Guid("5e9c10d4-3b0a-4ccb-8a77-fb2d7e702c6b")
                        });
                });

            modelBuilder.Entity("Entities.Models.Instructor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstMidName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("FirstName");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5b225eaa-ca3e-461d-85be-fb4608f87148"),
                            Email = "kabercrombie@contosouniversity.edu",
                            FirstMidName = "Kim",
                            HireDate = new DateTime(1995, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Abercrombie"
                        },
                        new
                        {
                            Id = new Guid("2a12c3f2-fc7a-4bd2-9f66-21a9c79d1893"),
                            Email = "ffakhouri@contosouniveristy.edu",
                            FirstMidName = "Fadi",
                            HireDate = new DateTime(2002, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Fakhouri"
                        },
                        new
                        {
                            Id = new Guid("63b92923-68a5-4053-9bf7-5e41c4fe1d91"),
                            Email = "rharui@contosouniversity.edu",
                            FirstMidName = "Roger",
                            HireDate = new DateTime(1998, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Harui"
                        },
                        new
                        {
                            Id = new Guid("e24a644d-9a45-4f66-966c-580fd191573a"),
                            Email = "ckapoor@contosouniversity.edu",
                            FirstMidName = "Candace",
                            HireDate = new DateTime(2001, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kapoor"
                        },
                        new
                        {
                            Id = new Guid("455dfcc1-552a-45fa-b94e-d973906490cc"),
                            Email = "rzheng@contosouniversity.edu",
                            FirstMidName = "Roger",
                            HireDate = new DateTime(2004, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Zheng"
                        });
                });

            modelBuilder.Entity("Entities.Models.OfficeAssignment", b =>
                {
                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("InstructorId");

                    b.ToTable("OfficeAssignments");

                    b.HasData(
                        new
                        {
                            InstructorId = new Guid("2a12c3f2-fc7a-4bd2-9f66-21a9c79d1893"),
                            Location = "Smith 17"
                        },
                        new
                        {
                            InstructorId = new Guid("63b92923-68a5-4053-9bf7-5e41c4fe1d91"),
                            Location = "Gowan 27"
                        },
                        new
                        {
                            InstructorId = new Guid("e24a644d-9a45-4f66-966c-580fd191573a"),
                            Location = "Thompson 304"
                        });
                });

            modelBuilder.Entity("Entities.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstMidName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("06917677-cdd6-4523-91b8-88d6d0a912d2"),
                            Email = "calexander@contosouniversity.edu",
                            EnrollmentDate = new DateTime(2010, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstMidName = "Carson",
                            LastName = "Alexander"
                        },
                        new
                        {
                            Id = new Guid("798acf1b-7339-44bd-8367-7132a978d7b1"),
                            Email = "malonso@contosouniversity.edu",
                            EnrollmentDate = new DateTime(2012, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstMidName = "Meredith",
                            LastName = "Alonso"
                        },
                        new
                        {
                            Id = new Guid("2a36409f-6732-459b-b7d1-a561c521a3cb"),
                            Email = "aanand@contosouniversity.edu",
                            EnrollmentDate = new DateTime(2013, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstMidName = "Arturo",
                            LastName = "Anand"
                        },
                        new
                        {
                            Id = new Guid("7d84360e-4967-4c7b-8e4c-0f085de7ca4d"),
                            Email = "gbarzdukas@contosouniversity.edu",
                            EnrollmentDate = new DateTime(2012, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstMidName = "Gytis",
                            LastName = "Barzdukas"
                        },
                        new
                        {
                            Id = new Guid("7a1be69a-38ac-4cde-a105-615de38c2d12"),
                            Email = "yli@contosouniversity.edu",
                            EnrollmentDate = new DateTime(2012, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstMidName = "Yan",
                            LastName = "Li"
                        },
                        new
                        {
                            Id = new Guid("5e9c10d4-3b0a-4ccb-8a77-fb2d7e702c6b"),
                            Email = "pjustice@contosouniversity.edu",
                            EnrollmentDate = new DateTime(2011, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstMidName = "Peggy",
                            LastName = "Justice"
                        },
                        new
                        {
                            Id = new Guid("53cea385-aa61-4e81-ba7a-38d7ed60ce4f"),
                            Email = "lnorman@contosouniversity.edu",
                            EnrollmentDate = new DateTime(2013, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstMidName = "Laura",
                            LastName = "Norman"
                        },
                        new
                        {
                            Id = new Guid("554039c7-cba1-4404-9fbe-21918a9190f7"),
                            Email = "nolivetto@contosouniversity.edu",
                            EnrollmentDate = new DateTime(2005, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstMidName = "Nino",
                            LastName = "Olivetto"
                        });
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1ec3030e-17af-426d-8960-86882aa7bd72",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "adafea42-ab4e-4146-8d18-fa1d7f45b5f1",
                            Name = "Professor",
                            NormalizedName = "PROFESSOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Course", b =>
                {
                    b.HasOne("Entities.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Entities.Models.CourseAssignment", b =>
                {
                    b.HasOne("Entities.Models.Course", "Course")
                        .WithMany("CourseAssignments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Instructor", "Instructor")
                        .WithMany("CourseAssignments")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Entities.Models.Department", b =>
                {
                    b.HasOne("Entities.Models.Instructor", "Administrator")
                        .WithMany()
                        .HasForeignKey("InstructorId");

                    b.Navigation("Administrator");
                });

            modelBuilder.Entity("Entities.Models.Enrollment", b =>
                {
                    b.HasOne("Entities.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Entities.Models.OfficeAssignment", b =>
                {
                    b.HasOne("Entities.Models.Instructor", "Instructor")
                        .WithOne("OfficeAssignment")
                        .HasForeignKey("Entities.Models.OfficeAssignment", "InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Course", b =>
                {
                    b.Navigation("CourseAssignments");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Entities.Models.Department", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Entities.Models.Instructor", b =>
                {
                    b.Navigation("CourseAssignments");

                    b.Navigation("OfficeAssignment");
                });

            modelBuilder.Entity("Entities.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
